sudo: required
services:
- docker
language: java
cache:
    directories:
    - $HOME/.m2
jdk:
- oraclejdk8
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push lukasverstraete/weather-destination